# Generated by Django 4.2.5 on 2023-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination_n',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='whl_distribution_n',
            options={'managed': True},
        ),
    ]
