# Generated by Django 4.2.5 on 2023-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_destination_n_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_n',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whl_distribution_n',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
