# Generated by Django 4.2.5 on 2023-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_destination_n_id_alter_whl_distribution_n_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblsocinvoicing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wholesale_tariffe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
