# Generated by Django 4.2.5 on 2023-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tariffe_id_alter_tblsocinvoicing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='profile_images/'),
        ),
    ]
