# Generated by Django 4.2.3 on 2023-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_tariffpercaton_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riepilogo',
            name='id_revenues',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
