# Generated by Django 4.2.3 on 2023-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_riepilogo_id_revenues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riepilogo',
            name='co_costum',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='riepilogo',
            name='co_departure',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='riepilogo',
            name='co_destination',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='riepilogo',
            name='co_parking',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='riepilogo',
            name='id_revenues',
            field=models.CharField(default=None, max_length=35, null=True),
        ),
    ]
