column_mapping = {
    "brand": "Brand",
    "customer_type": "Customer type",
    "customer_code": "Customer code",
    "store_id": "Store ID",
    "customer_description": "Customer description",
    "store_description": "Store description",
    "city_code": "City code",
    "country": "Country",
    "invoice": "Invoice #",
    "logistics_invoice": "Logistic Invoice #",
    "logistics_company": "Logistic Company",
    "invoice_date": "Invoice date",
    "ipo_invoice": "IPO Invoice #",
    "ipo_company": "IPO Company",
    "lgi_invoice": "LGI Invoice #",
    "lgi_company": "LGI Company",
    "prebolla_pda": "Prebolla_PDA",
    "purchase_order": "Purchase Order",
    "department_code": "Department code",
    "department_description": "Department description",
    "cites": "Cites",
    "pieces": "Pieces",
    "parcels": "Parcels",
    "gross_weight_kg": "Gross weight Kg.",
    "volume_m3": "Volume m3",
    "shp_status": "Shp.status",
    "shp_type_code": "Shp.Type code",
    "shp_type_desc": "Shp.Type desc.",
    "carrier": "Carrier",
    "master_shp_n": "Master Shp.N.",
    "shp_n": "Shp.N.",
    "dep_apt": "Dep.Apt",
    "des_apt": "Des.Apt",
    "rd_due_date": "RD Due date",
    "carrier_due_date": "Carrier Due date",
    "status_a": "Status A=Available date",
    "status_b": "Status B=Booking date",
    "booking_user": "Booking user",
    "status_c": "Status C=confirmed date",
    "req_delivery_date": "Req. delivery date",
    "changed_status_to_t_110": "110_Changed status to T",
    "pickup_tms_490": "490_Pickup TMS",
    "pickup_from_ff_500": "500_Pickup from FF",
    "atd_from_ff_hub_501": "501_ATD from FF hub",
    "eta_loc_ff_platform_508": "508_ETA Loc FF Platform",
    "ata_local_ff_platform_530": "530_ATA Local FF platform",
    "deliv_to_whs_598": "598_deliv.to WHs",
    "deliv_to_store_599": "599_deliv.to store",
    "cs_code": "CS code",
    "groupage": "Groupage",
    "sender_cust_code": "Sender cust.code",
    "sender_store_id": "Sender store ID",
    "sender_cust_desc": "Sender cust.desc.",
    "sender_store_desc": "Sender store desc.",
    "sender_country": "Sender country",
    "status_c_to_a": "Status C to A",
    "logistic_no_merch": "Logistic NO Merch",
    "service_code": "Service code",
    "service_level": "Service level",
    "origin_invoice": "Origin invoice",
    "outbound_delivery": "Outbound delivery",
    "destination": "Destination",
    "execution_date": "Execution date",
    "user": "User",
    "deviation_code": "Deviation Code",
    "deviation_date": "Deviation Date",
    "category": "Category",
    "responsability": "Responsability",
    "gross_performance": "Gross Performance",
    "net_performance": "Net Performance",
    "other_deviations": "Other Deviations",
    "comment": "Comment",
    "custom_id":"ID",
    "magazzino_di_carico": "MAGAZZINO DI CARICO",
    "lead_time": "LEAD TIME",
    "rdduedate_vs_carduedate":"RDDUEDATE vs CARDUEDATE",
    "rdduedate_vs_required":"RDDUEDATE vs REQUIRED",
    "required_vs_deliv_to_store_599":"REQUIRED vs DELIV TO STORE 599",
}

optional = {
    "shp_status": "Shp.status",
    "shp_type_code": "Shp.Type code",
    "shp_type_desc": "Shp.Type desc.",
    "carrier": "Carrier",
    "master_shp_n": "Master Shp.N.",
    "shp_n": "Shp.N.",
    "dep_apt": "Dep.Apt",
    "des_apt": "Des.Apt",
    "rd_due_date": "RD Due date",
    "carrier_due_date": "Carrier Due date",
    "status_a": "Status A=Available date",
    "status_b": "Status B=Booking date",
    "booking_user": "Booking user",
    "status_c": "Status C=confirmed date",
    "req_delivery_date": "Req. delivery date",
    "changed_status_to_t_110": "110_Changed status to T",
    "pickup_tms_490": "490_Pickup TMS",
    "pickup_from_ff_500": "500_Pickup from FF",
    "atd_from_ff_hub_501": "501_ATD from FF hub",
    "eta_loc_ff_platform_508": "508_ETA Loc FF Platform",
    "ata_local_ff_platform_530": "530_ATA Local FF platform",
    "deliv_to_whs_598": "598_deliv.to WHs",
    "deliv_to_store_599": "599_deliv.to store",
    "cs_code": "CS code",
    "groupage": "Groupage",
    "sender_cust_code": "Sender cust.code",
    "sender_store_id": "Sender store ID",
    "sender_cust_desc": "Sender cust.desc.",
    "sender_store_desc": "Sender store desc.",
    "sender_country": "Sender country",
    "status_c_to_a": "Status C to A",
    "logistic_no_merch": "Logistic NO Merch",
    "service_code": "Service code",
    "service_level": "Service level",
    "origin_invoice": "Origin invoice",
    "outbound_delivery": "Outbound delivery",
    "destination": "Destination",
    "execution_date": "Execution date",
    "user": "User",
    "deviation_code": "Deviation Code",
    "deviation_date": "Deviation Date",
    "category": "Category",
    "responsability": "Responsability",
    "gross_performance": "Gross Performance",
    "net_performance": "Net Performance",
    "other_deviations": "Other Deviations",
    "comment": "Comment",
    "custom_id":"ID"
}

